[package]
name = "ruscii"
version = "0.1.0"
authors = ["Luis Enrique Muñoz Martín <lemunozm@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.13"
device_query = "0.1.3"
lazy_static = "1.4.0"
