[package]
name = "ruscii"
version = "0.1.0"
authors = ["Luis Enrique Muñoz Martín <lemunozm@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.14"
device_query = "0.1"
num = "0.2"

[dev-dependencies]
rand = "0.7.2"

